#!/bin/sh
# spawns a dmenu prompt asking to choose between shutdown, reboot, logout or abort

color0="black"
color9="darkred"

# load xresources colors
# . "${XDG_CACHE_HOME}/wal/colors.sh"

chosen=$(printf "cancel\\npoweroff\\nreboot\\nlogout" | dmenu_run -nb "$color0" -sb "$color9" -sf white -nf gray -i -p "How do you want to quit?")

case "$chosen" in
	poweroff) poweroff;;
	reboot) reboot;;
	logout) killall Xorg;;
	cancel) ;;
esac
